export enum Unit {
  Teaspoon = "tsp.",
  Tablespoon = "tbsp.",
  FluidOunce = "fl oz",
  Gill = "gill",
  Cup = "cup",
  Pint = "pint",
  Quart = "qt",
  Gallon = "gallon",
  Milliliter = "mL",
  Liter = "L",
  DeciLiter = "deciliter",
  Pound = "lb",
  Ounce = "oz",
  Milligram = "mg",
  Gram = "g",
  Kilogram = "kg",
  Millimeter = "mm",
  Centimeter = "cm",
  Meter = "m",
  Inch = "inch",
}
